# Whether to tabcomplete offline player names.
# On Paper and other server implementation that implement the Paper API this will be done asynchronously,
# causing less stress on the server's main thread, thus preventing lag.
tabcomplete-offline-players: true

# Whether InvSee++ will let you spectate inventories of players who are offline.
enable-offline-player-support: true
# Whether InvSee++ will let you spectate inventories of players who never player on the server before.
enable-unknown-player-support: true

# Default titles for spectator inventories.
titles:
  inventory: "<player>'s inventory"
  enderchest: "<player>'s enderchest"

# Default templates for spectator inventories.
# legend:
#   inventory:
#     - i_xx is a regular inventory 'container' slot (xx being the slot number)
#     - a_x is an armour slot: b for boots, l for leggings, c for chest and h for helmet
#     - oh is the offhand slot
#     - c is the cursor slot
#     - p_xx is a 'personal' slot, where the contents of the player's crafting items / anvil items / enchanting table items / etc. live
#     - _ is an unused slot
#   enderchest:
#     - e_xx is a regular enderchest 'container' slot (xx being the slot number)
#   Note that normally a player's enderchest is only 3*9=27 slots in size, but on Purpur this can go up to 54.
templates:
  inventory: |
    i_00 i_01 i_02 i_03 i_04 i_05 i_06 i_07 i_08
    i_09 i_10 i_11 i_12 i_13 i_14 i_15 i_16 i_17
    i_18 i_19 i_20 i_21 i_22 i_23 i_24 i_25 i_26
    i_27 i_28 i_29 i_30 i_31 i_32 i_33 i_34 i_35
    a_b  a_l  a_c  a_h  oh   c    _    _    _   
    p_00 p_01 p_02 p_03 p_04 p_05 p_06 p_07 p_08
  enderchest: |
    e_00 e_01 e_02 e_03 e_04 e_05 e_06 e_07 e_08
    e_09 e_10 e_11 e_12 e_13 e_14 e_15 e_16 e_17
    e_18 e_19 e_20 e_21 e_22 e_23 e_24 e_25 e_26
    e_27 e_28 e_29 e_30 e_31 e_32 e_33 e_34 e_35
    e_36 e_37 e_38 e_39 e_40 e_41 e_42 e_43 e_44
    e_45 e_46 e_47 e_48 e_49 e_50 e_51 e_52 e_53

# Logging options
logging:
  # Pick one from: [LOG_NEVER, LOG_ON_CLOSE, LOG_EVERY_CHANGE]
  granularity: LOG_ON_CLOSE
  # Pick zero or more from: [CONSOLE, SERVER_LOG_FILE, PLUGIN_LOG_FILE, SPECTATOR_LOG_FILE]
  output: [PLUGIN_LOG_FILE]