# Whether to tabcomplete offline player names.
# On Paper and other server implementation that implement the Paper API this will be done asynchronously,
# causing less stress on the server's main thread, thus preventing lag.
tabcomplete-offline-players: true
